import { AddAddUserFormWrapper, AlertBlock, Header, ModalWindow, UserDataTableWrapper } from "@/components";
import PageAnimationWrapper from "@/components/PageAnimationWrapper/"
import Head from "next/head";
import { useRouter } from "next/router";
import { useSession } from 'next-auth/react';
import { useEffect } from "react";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const UsersPage = () => {

  return (
    <AuthProvider>
      <PageAnimationWrapper>
        <Head>
          <title>CRUD APP</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
          <Header />
          <AlertBlock />
          <UserDataTableWrapper />
          <ModalWindow>
            <AddAddUserFormWrapper />
          </ModalWindow>
        </>
      </PageAnimationWrapper>
    </AuthProvider>
  )
};

export default UsersPage;