import { PageAnimationWrapper } from '@/components';
import LoginForm from '@/components/LoginForm';
import ProvidersBlock from '@/components/ProvidersBlock';
import RegistrationForm from '@/components/RegistrationForm';
import { Box, Button, Flex, Text, useColorMode, useColorModeValue } from '@chakra-ui/react';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import styles from '../styles/bgAnimation.module.css';
import { LinkStyleButtonStyles } from '@/styles/additionalStyles';
import { MoonIcon, SunIcon } from '@chakra-ui/icons';
import { AnimatePresence, motion } from 'framer-motion';


export default function Home() {
  const session = useSession();
  const router = useRouter();
  const [isRegistration, setFormType] = useState(false);
  const bgColor = useColorModeValue('white', '#1a1a1a');


  const formOpacityAnimation = {
    key: 'formOpacityAnimation',
    initial: { opacity: 0 },
    animate: { opacity: 1 },
    exit: { opacity: 0 },
    transition: { duration: 1 }
  }

  useEffect(() => {
    if (session.status === 'authenticated') {
      router.push('/users');
    }
  }, [session.status]);

  const { toggleColorMode, colorMode } = useColorMode();
  const isLight = colorMode === 'light';

  return (
    <>
      <Head>
        <title>CRUD APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageAnimationWrapper>
        <div className={isLight ? styles.animation_container : styles.animation_container_dark}>
          <Button {...LinkStyleButtonStyles} position={'absolute'} top='1em' left='1em'
            onClick={() => toggleColorMode()}>
            {
              isLight ?
                <MoonIcon color='white' fontSize='1.5em' _hover={{ cursor: 'pointer', color: '#EEE' }} transition='.33s' />
                :
                <SunIcon color='white' fontSize='1.5em' _hover={{ cursor: 'pointer', color: '#EEE' }} transition='.33s' />
            }
          </Button>
          <AnimatePresence>
            <motion.div animate={{ opacity: 1 }} initial={{ opacity: 0 }}>
              <Box backgroundColor={bgColor} w='50%' p='2em' m='0 auto' borderRadius='.5em' zIndex={999}>
                {
                  isRegistration ?
                    <RegistrationForm successHandler={() => setFormType(false)} />
                    :
                    <LoginForm />
                }
                <ProvidersBlock isRegistration={isRegistration} />
                <Flex alignItems='center' w='100%' gap='.5em' justifyContent='center'>
                  {
                    !isRegistration ?
                      <>
                        <Text>Don&apos;t have an account yet?</Text>
                        <Button variant='link' onClick={() => setFormType(true)}>Sign up now</Button>
                      </>
                      :
                      <>
                        <Text>Already have an account?</Text>
                        <Button variant='link' onClick={() => setFormType(false)}>Sign in now</Button>
                      </>
                  }
                </Flex>
              </Box>
            </motion.div>
          </AnimatePresence>
          {/* <div className={isLight ? styles.wave : styles.wave_dark}></div>
          <div className={isLight ? styles.wave : styles.wave_dark}></div>
          <div className={isLight ? styles.wave : styles.wave_dark}></div> */}
        </div>
      </PageAnimationWrapper >
    </>
  )
}
